create extension if not exists pgcrypto;
create table if not exists public.staff(id uuid primary key default gen_random_uuid(),name text not null,role text default '館員',slug text unique,bio text,quote text,services text[] default '{}',photo_1 text,photo_2 text,photo_3 text,active boolean default true,accepting_reservations boolean default true,sort_order int default 0,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.staff_unavailability(id uuid primary key default gen_random_uuid(),staff_id uuid references public.staff(id) on delete cascade,starts_at timestamptz not null,ends_at timestamptz not null,reason text,recurrence text,created_at timestamptz default now(),constraint valid_range check(ends_at>starts_at));
create table if not exists public.reservations(id uuid primary key default gen_random_uuid(),guest_name text not null,contact text,staff_id uuid references public.staff(id),staff_name text,service_name text not null,price bigint default 0,starts_at timestamptz not null,ends_at timestamptz not null,note text,status text default 'pending',created_at timestamptz default now(),constraint reservation_range check(ends_at>starts_at));
create table if not exists public.orders(id uuid primary key default gen_random_uuid(),guest_name text not null,contact text,items jsonb not null default '[]',total bigint default 0,note text,status text default 'pending',created_at timestamptz default now());
create table if not exists public.announcements(id uuid primary key default gen_random_uuid(),title text not null,content text,published boolean default true,created_at timestamptz default now());
create table if not exists public.site_settings(key text primary key,value jsonb not null default 'null',updated_at timestamptz default now());
insert into public.site_settings(key,value) values ('venue',jsonb_build_object('name','眠楓館','address','穹頂皓天 7區22號','business_status','open','business_hours','依招募板公告為主')) on conflict(key) do nothing;
insert into public.staff(name,role,slug,active,accepting_reservations,sort_order) values ('羽鶴璃久','館主','riku',true,false,1),('微','館員','wei',true,true,2),('花形','館員','hanagata',true,true,3) on conflict(slug) do nothing;
alter table public.staff enable row level security;alter table public.staff_unavailability enable row level security;alter table public.reservations enable row level security;alter table public.orders enable row level security;alter table public.announcements enable row level security;alter table public.site_settings enable row level security;
create policy "public read active staff" on public.staff for select using(active=true);
create policy "public read blocks" on public.staff_unavailability for select using(true);
create policy "public create reservation" on public.reservations for insert with check(true);
create policy "public create order" on public.orders for insert with check(true);
create policy "public read announcements" on public.announcements for select using(published=true);
create policy "public read settings" on public.site_settings for select using(true);
create policy "admin staff all" on public.staff for all to authenticated using(true) with check(true);
create policy "admin blocks all" on public.staff_unavailability for all to authenticated using(true) with check(true);
create policy "admin reservations all" on public.reservations for all to authenticated using(true) with check(true);
create policy "admin orders all" on public.orders for all to authenticated using(true) with check(true);
create policy "admin announcements all" on public.announcements for all to authenticated using(true) with check(true);
create policy "admin settings all" on public.site_settings for all to authenticated using(true) with check(true);
